### ISSUE TITLE
Design QA

### ISSUE THREAD

**Issue by dahyeseol** [goodatlas/zeroth-design#2]
<img width="425" alt="2018-11-20 6 11 41" src="https://user-images.githubusercontent.com/26474611/48763351-6ecc7780-ecf0-11e8-9d55-e678b460a5d4.png">

- [ ] '카드수정' in dashboard home payment card has to be '제한없이 사용하기' when user doesn't connect the card. 카드수정 <-> 제한없이 사용하기

**Comment by beomjungil** [comment]
It moved to https://github.com/goodatlas/atlas-cloud-console/issues/30
